### PR TITLE
refactor: update user default role

### PR DESCRIPTION
**Pull request by 4msar**
This PR updated the default role usage by the slug name of Role model.

Id is not constant all the time sometimes it was change due to DB auto increment & etc.

### CODE REVIEW

**Comment by hasinhayder** [comment]
Thank you for this excellent PR.  I will check and merge it soon. 

Appreciate the effort :)

**Comment by hasinhayder** [comment]
Also `UsersSeeder.php` needs the following changes

```
class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('users')->truncate();
        Schema::enableForeignKeyConstraints();

        $user = User::create([
            'email'=>'admin@hydra.project',
            'password'=>Hash::make('hydra'),
            'name'=>'Hydra Admin'
        ]);
        $user->roles()->attach(Role::where('slug','admin')->first());
    }
}
```

**Comment by 4msar** [comment]
@hasinhayder brother, I have updated the PR.

**Comment by hasinhayder** [comment]
Thanks, merged

**Pull request merged**
